#               __
#  __ __  __   / /
#  \ V / / _| / _ \
#   \_/  \__| \___/

tasks:
   - name: cloggy
     before:  bash clogrc/gitpod/tasks.sh before
     init:    bash clogrc/gitpod/tasks.sh init
     command: bash clogrc/gitpod/tasks.sh command

vscode:
  extensions:
    - dbaeumer.vscode-eslint            # lint javascript code
    - piersdeseilligny.betterfountain   # screen writer plugin
    - stkb.rewrap                       # wrap markdown at column boundaries
    - ms-toolsai.jupyter                # jupyter notebook support
    - mads-hartmann.bash-ide-vscode     # bash scripting helper